version: "3.9"
services:
  web:
    build: .
    ports:
      - "8000:5000"
    container_name: "webapp"
    environment:
      - POSTGRES_DB=hello_flask_dev
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  redis:
    image: "redis:alpine"
    container_name: redis
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_DB=hello_flask_dev
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
    container_name: db
volumes:
  db:
    driver: local
